name: Check build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Install a modern Node on the runner for this job
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'   # optional: caches pnpm store
          
      # Enable pnpm via corepack (bundled with Node >=16.17)
      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate

      - name: Build project
        run: |
          pnpm install
          pnpm run build
